name: Run Importer
on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - env:
        LAMP_ACCESS_KEY: ${{ secrets.LAMP_ACCESS_KEY }}
        LAMP_SECRET_KEY: ${{ secrets.LAMP_SECRET_KEY }}
        LAMP_SERVER_ADDRESS: ${{ secrets.LAMP_SERVER_ADDRESS }}
      run: |
        pip install requests lamp-core
        python main.py
