name: Test
on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
        API_URL: ${{ secrets.API_URL }}
      run: |
        python -m pip install --upgrade pip
        pip install requests
        python main.py
